export const AUTHORS = [
  'Marc Aurèle',
  'Sénèque',
  'Épictète',
  'Lao-Tseu',
  'Bouddha',
  'Confucius',
  'Gandhi',
  'Nelson Mandela',
  'Martin Luther King Jr.',
  'Winston Churchill',
  'Dalton Tran',
  'Albert Camus',
  'Victor Hugo',
  'Honoré de Balzac',
  'Léopold Sedar Senghor',
  'Aimé Césaire',
  'Henri Bergson',
  'Simone de Beauvoir',
  'Jean-Paul Sartre',
  'Albert Schweitzer',
  'Mark Twain',
  'Ralph Waldo Emerson',
  'Henry David Thoreau',
  'Maya Angelou',
  'Henning Mankell',
  'Charles Bukowski',
  'Pablo Neruda',
  'Ted Hughes',
  'Jiddu Krishnamurti',
  'Eckhart Tolle',
  'Deepak Chopra',
  'Wayne Dyer',
  'Louise Hay',
  'Mère Teresa',
  'Paul Coelho',
  'Paulo Freire',
  'Anthony de Mello',
  'Thich Nhat Hanh',
  'Howard Thurman',
  'Mahatma Gandhi',
  'Dalai Lama',
  'Rumi',
  'Kahlil Gibran',
  'Osho',
  'Fyodor Dostoyevsky',
  'Leo Tolstoy',
  'Anton Chekhov',
  'Vladimir Nabokov',
  'Joseph Brodsky',
  'Bulat Okudzhava',
  'Susan Sontag',
  'Joan Didion',
  'James Baldwin',
  'Zora Neale Hurston',
  'Nella Larsen',
  'Rita Dove',
  'Toni Morrison',
  'Langston Hughes',
  'Gabriel García Márquez',
  'Jorge Luis Borges',
  'Isabel Allende',
  'Gustave Flaubert',
  'George Sand',
  'Albert Einstein',
  'Isaac Newton',
  'Nikola Tesla',
  'Thomas Edison',
  'Benjamin Franklin',
  'Abraham Lincoln',
  'Theodore Roosevelt',
  'Eleanor Roosevelt',
  'Malcolm X',
  'Betty Shabazz',
  'Bayard Rustin',
  'César Chavez',
  'Malcolm Macdonald',
  'Florence Nightingale',
  'Amelia Earhart',
  'Marie Curie',
  'Rosalind Franklin',
  'Rachel Carson',
  'Jane Goodall',
  'Oprah Winfrey',
  'Malala Yousafzai',
  'Greta Thunberg',
  'Ellen Johnson Sirleaf',
  'Aung San Suu Kyi',
];

export const QUOTES = [];

export const quotesCount = () => QUOTES.length;

export const randomQuote = () => {
  if (!QUOTES.length) return null;
  const q = QUOTES[Math.floor(Math.random() * QUOTES.length)];
  if (!q) return null;
  return { text: String(q.text || ''), author: String(q.author || '') };
};
